name: Release Shared Types Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Generate types
      run: yarn build:types

    - name: Get diff
      id: git-diff
      run: |
        echo "GIT_DIFF=$(git diff --name-only | grep shared-types/index.d.ts)" >> $GITHUB_ENV
    - name: Conditional
      if: ${{ env.GIT_DIFF }}
      run: |
        echo "${{ env.GIT_DIFF }}"
